### ISSUE TITLE
Sometimes image rendering breaks

### ISSUE THREAD

**Issue by pfloride** [TwicPics/components#111]
Hi there, we've had an issue come up with the way some images are rendered. It's not easy reproducible and also doesn't really seem to be a problem with the images themselves (f.e. the same image in the same browser is broken in the prod env but not in stage). Has this behaviour come up for somebody else before?
 
![image](https://github.com/user-attachments/assets/4a8664d2-9e03-41b9-9fa2-4df2d3f4cad9)

https://github.com/user-attachments/assets/32d4deb7-7f6a-4cd5-94fe-b3141ac18523

**Comment by mbgspcii** [comment]
Hi @pfloride 
Thank you for opening this issue.
No, this behaviour has not yet been reported.
Can you tell me more?
- Is this a use of [TwicPics components](https://www.npmjs.com/package/@twicpics/components)? (I don't see any LQIPs, hence my question).
- Which framework do you use?

Could you share a link with us so that we can take a closer look at this case?

**Comment by pfloride** [comment]
Hello @mbgspcii,
Thanks for the fast response! A colleague of mine was able to pinpoint the issue this morning and it actually seems to be a bug of the API / image transformation. We recently went through our codebase and added the `background=white` transformation to all TwicPics URLs. We had them in there before, but not everywhere and when refactoring, we've change the parameter order.

The old URLs always had the `max-resize=600` transformation before the `background=white` one. Changing around the order triggers the bug. Example:

- Broken: https://levejo.twic.pics/products/P000312002_2024-04-04_hero.png?twic=v1/resize-max=600/background=white/output=webp
- Correct: https://levejo.twic.pics/products/P000312002_2024-04-04_hero.png?twic=v1/background=white/resize-max=600/output=webp

This issue is not affecting all images, just a seemingly random subset of them.

Can this issue maybe be escalated to the right team from here or should I better report it over the website?

**Comment by mbgspcii** [comment]
Hi @pfloride 
Okay, so it's a processing problem that I'm passing on to the right people.
For this kind of issue (other than TwicPIcs Components issue) you should ask [here](https://help.twicpics.com/en/) (you must be logged in to your TwicPics account).
We'll get back to you as soon as we have some insight into the problem you're raising.

Just one question. I went [here](https://levejo.de/de/p/teko-plastic-plastikeimer-10-liter-schwarz-P000715006) and i checked the generated html.
Did you modified the TwicPics Components code in order to generate a custom LQIP ? It is stange to have https://levejo.twic.pics/products/P000715006_2024-05-10_hero.png?twic=v1/background=white/resize-max=600/output=web as a low quality placeholder. It should be https://levejo.twic.pics/base_images/2004213.webp?twic=v1/background=white/cover=1000x1000/output=preview (a lightweight svg version). Here you have a webp version too heavy to be used as a LQIP.
If you don't have modified the code, this is an issue we will have to fix.

Please keep me in touch about this.

Thans in advance.
