### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by juan-kreuzfahrtberater** [TwicPics/components#14]
I am currently trying to use the TwicImg component in a tsx / nuxt application i had to declare globally  a .d.ts file with the following content

`declare let TwicImg: any;`

i assume there should be a TwicImg type so that it can be used with tsx

**Comment by Strift** [comment]
I think I've had TypeScript auto-completion when using the React module, but not the Nuxt one. So maybe it's related to some Vue/Nuxt specifics.

**Comment by jaubourg** [comment]
@Strift it definitely is.

The Vue approach is to use a function that adds the TwicImg and TwicVideo to :
a) the global Vue object in Vue2
b) the App object in Vue3

The issue is that there never is an actual inclusion of TwicImg and/or TwicVideo in Vue / Nuxt. So there is no associated typescript definition.

I'm curious as to how other Vue components libs tackle the issue.

For reference, [here is the code for the installation of the components in Vue](https://github.com/TwicPics/components/blob/main/src/vue/index.ts#L12) (`register` is defined [here](https://github.com/TwicPics/components/blob/main/src/vue/register.ts#L7)).

**Comment by mbgspcii** [comment]
HI @juan-kreuzfahrtberater 

We have been working on the problem you have reported.

In order to be sure that it actually fixes your concern, can you provide us with a user case that we could test on our side before making a release ?

Sincerely yours.

Miguel
